version: '1'
meta:
  config_name: algo-trade-pipeline-default
  description: Default configuration for algo-trade-pipeline
  base_spec: specs/algo-trade-pipeline.yaml
execution:
  stages:
  - stage_id: indicator_calculation
    selected:
    - transform_id: calculate_rsi
      params:
        period: 14
